name: Security Check

on:
  push:
    paths:
      - 'skins/index.html'
  pull_request:
    paths:
      - 'skins/index.html'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Verify redirect file
        run: |
          if grep -q "csgo-skins.com" skins/index.html; then
            echo "✅ Redirect URL is correct"
          else
            echo "❌ Redirect URL modified!"
            exit 1
          fi
          
          if grep -q "ANGELKACS" skins/index.html; then
            echo "✅ Referral code is correct"
          else
            echo "❌ Referral code modified!"
            exit 1
          fi
